name: Beauty
favicon: null
layout_spectrum: 0.94286
typography_spectrum: 0.28286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7a8986'
    - '#615348'
    - '#f6b921'
    - '#080003'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: null
    url: null
