name: Beauty
favicon: null
layout_spectrum: 0.94286
typography_spectrum: 0.28286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#161a19'
    - '#6e5c48'
    - '#bbc4c9'
    - '#ff7e84'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.75
purpose:
  - name: engagement
    item: null
    url: null
